---
- hosts: all
  tasks:
  - name: Copy zshrc
    copy: src=files/zshrc dest=/home/vagrant/.zshrc
  - name: Set shell to zsh
    become: yes
    user: name=vagrant shell=/bin/zsh

  - name: Copy vimrc
    copy: src=files/vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant

  - name: Create vim dir
    file: path=/home/vagrant/.vim state=directory owner=vagrant group=vagrant

  - name: Upload vim directory
    copy: src=files/vim dest=/home/vagrant/ owner=vagrant group=vagrant

  - name: stat foo
    stat: path=/home/vagrant/vim
    register: foo_stat

  - name: Move vim to .vim
    become_user: vagrant
    command: mv /home/vagrant/vim /home/vagrant/.vim
    when: foo_stat.stat.exists

  - name: Cloning Vundle
    become_user: vagrant
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim

  - name: Run vundle install
    become_user: vagrant
    command: vim +PluginInstall! +qall

  - name: Download Sublime Installer
    copy: src=files/install_sublime_text.sh dest=/tmp/install_sublime_text.sh
  
  - name: Install Sublime
    become: yes
    command: bash /tmp/install_sublime_text.sh

  - name: Upload Gnome Shell theme
    copy: src=files/paper-gtk-theme_2.1+r263~daily~ubuntu16.04.1_all.deb dest=/tmp/paper-gtk-theme_2.1+r263~daily~ubuntu16.04.1_all.deb

  - name: Upload Gnome Icon Theme
    copy: src=files/paper-icon-theme_1.3+r567~daily~ubuntu16.04.1_all.deb dest=/tmp/paper-icon-theme_1.3+r567~daily~ubuntu16.04.1_all.deb

  - name: Install Theme
    become: yes
    command: dpkg -i /tmp/paper-gtk-theme_2.1+r263~daily~ubuntu16.04.1_all.deb

  - name: Install Icon Theme
    become: yes
    command: dpkg -i /tmp/paper-icon-theme_1.3+r567~daily~ubuntu16.04.1_all.deb

  - name: Set gtk-theme for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.interface gtk-theme "Paper"

  - name: Set desktop for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.wm.preferences theme "Paper"

  - name: Set icon-theme for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.interface icon-theme 'Paper'

  - name: Set title bar font for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Cantarell Bold 10'

  - name: Set interface font for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.interface font-name 'Cantarell Regular10'

  - name: Set interface document font for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.interface document-font-name 'Sans Regular 10'

  - name: Set background primary color for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.background primary-color "#425265"

  - name: Set background secondary color for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.background secondary-color "#425265"

  - name: Set background color shading type for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.background color-shading-type "solid"

  - name: Set background pictue options for vagrant user
    become_user: vagrant
    command: dbus-launch gsettings set org.gnome.desktop.background picture-options "none"
