---
- hosts: all
  tasks:
  - name: Copy zshrc
    copy: src=files/zshrc dest=/home/vagrant/.zshrc
  - name: Set shell to zsh
    become: yes
    user: name=vagrant shell=/bin/zsh

  - name: Copy vimrc
    copy: src=files/vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant

  #- name: Create vim dir
  #  file: path=/home/vagrant/.vim state=directory owner=vagrant group=vagrant

  - name: Upload vim directory
    copy: src=files/vim dest=/home/vagrant/ owner=vagrant group=vagrant

  - name: stat foo
    stat: path=/home/vagrant/vim
    register: foo_stat

  - name: Move vim to .vim
    become_user: vagrant
    command: mv /home/vagrant/vim /home/vagrant/.vim
    when: foo_stat.stat.exists

  - name: Cloning Vundle
    become_user: vagrant
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim

  - name: Run vundle install
    become_user: vagrant
    command: vim +PluginInstall! +qall

  - name: Download Sublime Installer
    command: wget https://gist.githubusercontent.com/svx/ce9874b86ed3fe9c14a19500545cd4bb/raw/099af474bd3be05d06b49f9aceb760dc27f1f159/install_sublime_text.sh -O /tmp/install_sublime_text.sh

  - name: Install Sublime
    command: bash /tmp/install_sublime_text.sh
